/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kesehatan;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        getPLtanggal();
        SpinnerModel value = new SpinnerNumberModel(0, 0, 24, 1);
        PLjam.setModel(value);
        getLapangan();
    }
    
    public void getLapangan(){
        try {
            String sql = "SELECT nama_lapangan FROM tb_jadwal";
            java.sql.Connection conn = config.configDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                PJlapangan.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR DATABASE");
        }
    }
    
    public boolean getValidatePL(){
        if(PLpesan.getText().equals("")){
            return false;
        }else if(PLjam.getValue().equals(0)){
            return false;
        }else if(PLdate.getSelectedItem().equals("Pilih Tanggal")){
            return false;
        }
        return true;
    }
    
    public void getPLtanggal(){
        Date date = new Date();
        SimpleDateFormat SDF = new SimpleDateFormat("YYYY-MM-dd");
        SimpleDateFormat tahun = new SimpleDateFormat("YYYY");
        Calendar cal = new GregorianCalendar(Integer.parseInt(tahun.format(date)), date.getMonth(), date.getDate());
        for (int i = 1; i <= 7; i++) {
           cal.add(Calendar.DAY_OF_MONTH, 1);
           PLdate.addItem(SDF.format(cal.getTime()));
           PJtanggal.addItem(SDF.format(cal.getTime()));
        }
    }
    
    public static void getLook(){
        try {
            UIManager.setLookAndFeel( new FlatDarculaLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PESAN_LAPANGAN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PLpesan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PLdate = new javax.swing.JComboBox<>();
        PLadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PLtable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        PLcount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PLchart = new javax.swing.JButton();
        PLjam = new javax.swing.JSpinner();
        PLedit = new javax.swing.JButton();
        PLdelete1 = new javax.swing.JButton();
        PESAN_JADWAL = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        PJtanggal = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        PJtable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        PJtxtcari = new javax.swing.JTextField();
        PJcari = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PJalamat = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        PJharga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        PJtotal = new javax.swing.JTextField();
        PJpesan = new javax.swing.JButton();
        PJhapus = new javax.swing.JButton();
        PJlapangan = new javax.swing.JComboBox<>();
        LIHAT_LAPORAN = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KESEHATAN");

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NAMA PRODUK");

        PLpesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("NILAI GIZI");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("TANGGAL");

        PLdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PLdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tanggal" }));

        PLadd.setBackground(new java.awt.Color(0, 0, 0));
        PLadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PLadd.setText("TAMBAH");
        PLadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLaddActionPerformed(evt);
            }
        });

        PLtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA ROTI", "NILAI GIZI", "TANGGAL"
            }
        ));
        PLtable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        PLtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PLtable);
        if (PLtable.getColumnModel().getColumnCount() > 0) {
            PLtable.getColumnModel().getColumn(0).setPreferredWidth(200);
            PLtable.getColumnModel().getColumn(1).setPreferredWidth(200);
            PLtable.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("JUMLAH DATA");

        PLcount.setBackground(new java.awt.Color(1, 66, 23));
        PLcount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PLcount.setForeground(new java.awt.Color(255, 255, 0));
        PLcount.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("KESEHATAN");

        PLchart.setBackground(new java.awt.Color(0, 0, 0));
        PLchart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PLchart.setText("INPUT");
        PLchart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLchartActionPerformed(evt);
            }
        });

        PLjam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        PLedit.setBackground(new java.awt.Color(0, 0, 0));
        PLedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PLedit.setText("EDIT");
        PLedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLeditActionPerformed(evt);
            }
        });

        PLdelete1.setBackground(new java.awt.Color(66, 0, 0));
        PLdelete1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PLdelete1.setText("HAPUS SEMUA");
        PLdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLdelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PESAN_LAPANGANLayout = new javax.swing.GroupLayout(PESAN_LAPANGAN);
        PESAN_LAPANGAN.setLayout(PESAN_LAPANGANLayout);
        PESAN_LAPANGANLayout.setHorizontalGroup(
            PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_LAPANGANLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_LAPANGANLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(PLcount)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_LAPANGANLayout.createSequentialGroup()
                        .addComponent(PLchart, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(516, 516, 516))))
            .addGroup(PESAN_LAPANGANLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(PESAN_LAPANGANLayout.createSequentialGroup()
                        .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PLdate, 0, 284, Short.MAX_VALUE)
                            .addComponent(PLjam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PLpesan, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PLadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PLedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PLdelete1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PESAN_LAPANGANLayout.setVerticalGroup(
            PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_LAPANGANLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_LAPANGANLayout.createSequentialGroup()
                        .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PLpesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLadd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PESAN_LAPANGANLayout.createSequentialGroup()
                                .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(PLjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(PLdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PLdelete1)))
                            .addComponent(PLedit))
                        .addGap(83, 83, 83)
                        .addGroup(PESAN_LAPANGANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(PLcount))
                        .addGap(106, 106, 106))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLchart)
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("GIZI", PESAN_LAPANGAN);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("TANGGAL");

        PJtanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PJtanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tanggal" }));
        PJtanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJtanggalActionPerformed(evt);
            }
        });

        PJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA ROTI", "NILAI GIZI", "TANGGAL"
            }
        ));
        PJtable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(PJtable);
        if (PJtable.getColumnModel().getColumnCount() > 0) {
            PJtable.getColumnModel().getColumn(0).setPreferredWidth(200);
            PJtable.getColumnModel().getColumn(1).setPreferredWidth(200);
            PJtable.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("TIMBANGAN");

        PJtxtcari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        PJcari.setBackground(new java.awt.Color(0, 26, 66));
        PJcari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PJcari.setText("CARI NAMA");
        PJcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJcariActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("LOKASI");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("BERAT TIMBANGAN");

        jScrollPane3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        PJalamat.setEditable(false);
        PJalamat.setColumns(20);
        PJalamat.setRows(5);
        jScrollPane3.setViewportView(PJalamat);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("HARGA");

        PJharga.setEditable(false);
        PJharga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("HARGA TOTAL");

        PJtotal.setEditable(false);
        PJtotal.setBackground(new java.awt.Color(255, 204, 0));
        PJtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PJtotal.setForeground(new java.awt.Color(51, 51, 51));

        PJpesan.setBackground(new java.awt.Color(1, 66, 23));
        PJpesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PJpesan.setText("INPUT");
        PJpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJpesanActionPerformed(evt);
            }
        });

        PJhapus.setBackground(new java.awt.Color(66, 0, 0));
        PJhapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PJhapus.setText("HAPUS");
        PJhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJhapusActionPerformed(evt);
            }
        });

        PJlapangan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PJlapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tanggal" }));
        PJlapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJlapanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PESAN_JADWALLayout = new javax.swing.GroupLayout(PESAN_JADWAL);
        PESAN_JADWAL.setLayout(PESAN_JADWALLayout);
        PESAN_JADWALLayout.setHorizontalGroup(
            PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PESAN_JADWALLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PESAN_JADWALLayout.createSequentialGroup()
                        .addComponent(PJtxtcari)
                        .addGap(649, 649, 649))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_JADWALLayout.createSequentialGroup()
                        .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PESAN_JADWALLayout.createSequentialGroup()
                                .addComponent(PJhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(PJpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_JADWALLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(59, 59, 59)
                                    .addComponent(PJtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(PJcari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_JADWALLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PJlapangan, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PESAN_JADWALLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PJtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(PESAN_JADWALLayout.createSequentialGroup()
                                .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PESAN_JADWALLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PJharga, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PESAN_JADWALLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_JADWALLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        PESAN_JADWALLayout.setVerticalGroup(
            PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_JADWALLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PJtxtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PJcari))
                .addGap(22, 22, 22)
                .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(PJtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(PJlapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PJharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(PESAN_JADWALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(PJtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PJhapus)
                    .addComponent(PJpesan))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("TIMBANGAN", PESAN_JADWAL);

        jLabel4.setText("LIHAT_LAPORAN");

        javax.swing.GroupLayout LIHAT_LAPORANLayout = new javax.swing.GroupLayout(LIHAT_LAPORAN);
        LIHAT_LAPORAN.setLayout(LIHAT_LAPORANLayout);
        LIHAT_LAPORANLayout.setHorizontalGroup(
            LIHAT_LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
            .addGroup(LIHAT_LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LIHAT_LAPORANLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        LIHAT_LAPORANLayout.setVerticalGroup(
            LIHAT_LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(LIHAT_LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LIHAT_LAPORANLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("LIHAT LAPORAN", LIHAT_LAPORAN);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(422, 422, 422))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PLaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLaddActionPerformed
        // TODO add your handling code here:
        if(getValidatePL() == true){
            DefaultTableModel model = (DefaultTableModel) PLtable.getModel();
            model.addRow(new Object[]{PLpesan.getText().toUpperCase(), PLjam.getValue(), PLdate.getSelectedItem()});
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            PLtable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            PLtable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
            PLtable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            PLpesan.setText(""); PLjam.setValue(0); PLdate.setSelectedIndex(0);
            PLcount.setText(String.valueOf(PLtable.getRowCount()));
        }else{
            JOptionPane.showMessageDialog(rootPane, "DATA TIDAK LENGKAP !!!");
        }
    }//GEN-LAST:event_PLaddActionPerformed

    private void PLeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLeditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) PLtable.getModel();
        int row = PLtable.getSelectedRow();
        model.setValueAt(PLpesan.getText(), row, 0);
        model.setValueAt(PLjam.getValue(), row, 1);
        model.setValueAt(PLdate.getSelectedItem(), row, 2);
    }//GEN-LAST:event_PLeditActionPerformed

    private void PLdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLdelete1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) PLtable.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
        PLcount.setText("0");
    }//GEN-LAST:event_PLdelete1ActionPerformed

    private void PLtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLtableMouseClicked
        // TODO add your handling code here:
        int row = PLtable.getSelectedRow();
        PLpesan.setText(PLtable.getValueAt(row, 0).toString());
        PLjam.setValue(PLtable.getValueAt(row, 1));
        PLdate.setSelectedItem(PLtable.getValueAt(row, 2).toString());
    }//GEN-LAST:event_PLtableMouseClicked

    private void PLchartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLchartActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<PLtable.getRowCount(); i++){
            try {
                String nama = String.valueOf(PLtable.getValueAt(i, 0));
                String jam = String.valueOf(PLtable.getValueAt(i, 1));
                String tanggal = String.valueOf(PLtable.getValueAt(i, 2));
                String sql = "INSERT INTO `tb_pesan` (`nama_pemesan`, `durasi_jam`, `tanggal`) VALUES ('"+nama+"',"+jam+",'"+tanggal+"')";
                java.sql.Connection conn = config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Data "+nama+" Sudah Masuk.");
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // DELETE
        DefaultTableModel dm = (DefaultTableModel) PLtable.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
        PLcount.setText("0");
    }//GEN-LAST:event_PLchartActionPerformed

    private void PJcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJcariActionPerformed
        // TODO add your handling code here:
        String nameCari = PJtxtcari.getText().toUpperCase();
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NAMA PEMESAN");
        model.addColumn("DURASI/JAM");
        model.addColumn("TANGGAL");
        
        if(nameCari.equals("")){
            try {
                String sql = "SELECT nama_pemesan, durasi_jam, tanggal FROM tb_pesan";
                java.sql.Connection conn = config.configDB();
                java.sql.Statement st = conn.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);
                
                while(rs.next()){
                    model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
                }
                PJtable.setModel(model);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                PJtable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                PJtable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                PJtable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TableColumnModel columnModel = PJtable.getColumnModel();
                columnModel.getColumn(0).setPreferredWidth(200);
                columnModel.getColumn(0).setMaxWidth(200);
                columnModel.getColumn(1).setPreferredWidth(200);
                columnModel.getColumn(1).setMaxWidth(200);
                columnModel.getColumn(2).setPreferredWidth(200);
                columnModel.getColumn(2).setMaxWidth(200);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "DATA ADA YANG BERMASALAH !!!");
            }
        }else{
            
            try {
                String sql = "SELECT nama_pemesan, durasi_jam, tanggal FROM tb_pesan WHERE nama_pemesan LIKE '%"+PJtxtcari.getText().toUpperCase()+"%'";
                java.sql.Connection conn = config.configDB();
                java.sql.Statement st = conn.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);
                
                while(rs.next()){
                    model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
                }
                PJtable.setModel(model);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                PJtable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                PJtable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                PJtable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TableColumnModel columnModel = PJtable.getColumnModel();
                columnModel.getColumn(0).setPreferredWidth(200);
                columnModel.getColumn(0).setMaxWidth(200);
                columnModel.getColumn(1).setPreferredWidth(200);
                columnModel.getColumn(1).setMaxWidth(200);
                columnModel.getColumn(2).setPreferredWidth(200);
                columnModel.getColumn(2).setMaxWidth(200);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "DATA ADA YANG BERMASALAH !!!");
            }
        
        }
        
    }//GEN-LAST:event_PJcariActionPerformed

    private void PJpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJpesanActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<PJtable.getRowCount(); i++){
            try {
                String nama = String.valueOf(PJtable.getValueAt(i, 0));
                String jam = String.valueOf(PJtable.getValueAt(i, 1));
                String tanggal = String.valueOf(PLtable.getValueAt(i, 2));
                String sql = "INSERT INTO `tb_laporan`(`id_laporan`, `id_pesan`, `id_jadwal`) VALUES ('[value-1]','[value-2]','[value-3]')  ";
                java.sql.Connection conn = config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Data "+nama+" Sudah Masuk.");
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // DELETE
        DefaultTableModel dm = (DefaultTableModel) PJtable.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }//GEN-LAST:event_PJpesanActionPerformed

    private void PJhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PJhapusActionPerformed

    private void PJtanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJtanggalActionPerformed
        // TODO add your handling code here:
        String tgkCari = (String) PJtanggal.getSelectedItem();
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NAMA PEMESAN");
        model.addColumn("DURASI/JAM");
        model.addColumn("TANGGAL");
        
        try {
                String sql = "SELECT nama_pemesan, durasi_jam, tanggal FROM tb_pesan WHERE tanggal LIKE '%"+tgkCari+"%'";
                java.sql.Connection conn = config.configDB();
                java.sql.Statement st = conn.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);
                
                while(rs.next()){
                    model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
                }
                PJtable.setModel(model);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                PJtable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
                PJtable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                PJtable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                TableColumnModel columnModel = PJtable.getColumnModel();
                columnModel.getColumn(0).setPreferredWidth(200);
                columnModel.getColumn(0).setMaxWidth(200);
                columnModel.getColumn(1).setPreferredWidth(200);
                columnModel.getColumn(1).setMaxWidth(200);
                columnModel.getColumn(2).setPreferredWidth(200);
                columnModel.getColumn(2).setMaxWidth(200);
        } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "DATA ADA YANG BERMASALAH !!!");
        }
    }//GEN-LAST:event_PJtanggalActionPerformed

    private void PJlapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJlapanganActionPerformed
        // TODO add your handling code here:
        String alamat_lapangan = (String) PJlapangan.getSelectedItem();
        Integer selectItem = PJtable.getSelectedRowCount();
        Integer row = PJtable.getSelectedRow();
        if(selectItem == 0){
            JOptionPane.showMessageDialog(rootPane, "PILIH SALAH SATU DATA");
        }else{
            try {
                String sql = "SELECT alamat_lapangan, harga FROM tb_jadwal WHERE nama_lapangan='"+alamat_lapangan+"'";
                java.sql.Connection conn = config.configDB();
                java.sql.Statement st = conn.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);

                while(rs.next()){
                    PJalamat.setText(rs.getString(1));
                    PJharga.setText(rs.getString(2));
                }
                Integer harga = Integer.parseInt(PJharga.getText());
                String jam = PJtable.getValueAt(row, 1).toString();
                Integer total = harga*Integer.parseInt(jam);
                PJtotal.setText(total.toString());
            } catch (NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERROR DATABASE" + e);
            }
            
            DefaultTableModel dm = (DefaultTableModel) PJtable.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
        }
        
    }//GEN-LAST:event_PJlapanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        Menu.getLook();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LIHAT_LAPORAN;
    private javax.swing.JPanel PESAN_JADWAL;
    private javax.swing.JPanel PESAN_LAPANGAN;
    private javax.swing.JTextArea PJalamat;
    private javax.swing.JButton PJcari;
    private javax.swing.JButton PJhapus;
    private javax.swing.JTextField PJharga;
    private javax.swing.JComboBox<String> PJlapangan;
    private javax.swing.JButton PJpesan;
    private javax.swing.JTable PJtable;
    private javax.swing.JComboBox<String> PJtanggal;
    private javax.swing.JTextField PJtotal;
    private javax.swing.JTextField PJtxtcari;
    private javax.swing.JButton PLadd;
    private javax.swing.JButton PLchart;
    private javax.swing.JLabel PLcount;
    private javax.swing.JComboBox<String> PLdate;
    private javax.swing.JButton PLdelete1;
    private javax.swing.JButton PLedit;
    private javax.swing.JSpinner PLjam;
    private javax.swing.JTextField PLpesan;
    private javax.swing.JTable PLtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
