/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import PemesananTiketPesawat.Login;
import database.ConnectDB;
import database.MyData;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        database.MyData data = new MyData();
        txt_pemail.setText(data.getEmail());
        getProfil();
    }
    
    public final void getProfil(){
        database.MyData data = new MyData();
        try {
            String sql = "select nama_lengkap, email, no_hp, password, alamat from tb_user where email='"+data.getEmail()+"'";
            java.sql.Connection conn=ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                txt_pnama.setText(res.getString(1));
                txt_pemail.setText(res.getString(2));
                txt_pnohp.setText(res.getString(3));
                txt_ppassword.setText(res.getString(4));
                txt_palamat.setText(res.getString(5));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "DATA PROFIL ADA YANG SALAH !!!"+e);
        }
    }
    
    public void getTableUser(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID USER");
        model.addColumn("NAMA LENGKAP");
        model.addColumn("NO HP");
        model.addColumn("EMAIL");
        model.addColumn("ALAMAT");
        try {
            String sql = "select id_user, nama_lengkap, no_hp, email, alamat from tb_user";
            java.sql.Connection conn= database.ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            tbl_user.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
        }
    }
    
    public void getTableTiket(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id_tiket");
        model.addColumn("bandara");
        model.addColumn("maskapai");
        model.addColumn("destinasi");
        model.addColumn("QTY");
        
        try {
            String sql = "select * from tb_tiket";
            java.sql.Connection conn= database.ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            tbl_tiket.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
        }
    }
    
    public void getTableRiwayat(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id_penerbangan");
        model.addColumn("nama_lengkap");
        model.addColumn("bandara");
        model.addColumn("maskapai");
        model.addColumn("destinasi");
        model.addColumn("tanggal");
        model.addColumn("jam");
        model.addColumn("kelas");
        model.addColumn("QTY");
        model.addColumn("harga_total");
        try {
            String sql = "select * from tb_riwayat";
            java.sql.Connection conn= database.ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5), res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});
            }
            tbl_riwayat.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_profil = new javax.swing.JButton();
        btn_datauser = new javax.swing.JButton();
        btn_tiket = new javax.swing.JButton();
        btn_riwayat = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PROFIL_ADMIN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_pnama = new javax.swing.JTextField();
        txt_pemail = new javax.swing.JTextField();
        txt_pnohp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_palamat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txt_ppassword = new javax.swing.JPasswordField();
        btn_pedit = new javax.swing.JButton();
        btn_psave = new javax.swing.JButton();
        DATA_USER = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();
        txt_ucari = new javax.swing.JTextField();
        btn_ucari = new javax.swing.JButton();
        cmb_upilih = new javax.swing.JComboBox<>();
        btn_uhapus = new javax.swing.JButton();
        btn_uedit = new javax.swing.JButton();
        select_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Uiduser = new javax.swing.JTextField();
        Unama = new javax.swing.JTextField();
        Unohp = new javax.swing.JTextField();
        Uemail = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ualamat = new javax.swing.JTextArea();
        btn_uedit1 = new javax.swing.JButton();
        DATA_TIKET = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_tcari = new javax.swing.JTextField();
        cmb_tpilih = new javax.swing.JComboBox<>();
        btn_tcari = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_tiket = new javax.swing.JTable();
        btn_thapus = new javax.swing.JButton();
        btn_ttambah = new javax.swing.JButton();
        btn_tedit = new javax.swing.JButton();
        RIWAYAT = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_riwayat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setText("AIRPAZ");

        btn_profil.setBackground(new java.awt.Color(102, 102, 102));
        btn_profil.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_profil.setForeground(new java.awt.Color(255, 255, 255));
        btn_profil.setText("PROFIL");
        btn_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profilActionPerformed(evt);
            }
        });

        btn_datauser.setBackground(new java.awt.Color(102, 102, 102));
        btn_datauser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_datauser.setForeground(new java.awt.Color(255, 255, 255));
        btn_datauser.setText("DATA USER");
        btn_datauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datauserActionPerformed(evt);
            }
        });

        btn_tiket.setBackground(new java.awt.Color(102, 102, 102));
        btn_tiket.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_tiket.setForeground(new java.awt.Color(255, 255, 255));
        btn_tiket.setText("DATA TIKET");
        btn_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tiketActionPerformed(evt);
            }
        });

        btn_riwayat.setBackground(new java.awt.Color(102, 102, 102));
        btn_riwayat.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_riwayat.setForeground(new java.awt.Color(255, 255, 255));
        btn_riwayat.setText("RIWAYAT");
        btn_riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_riwayatActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(153, 0, 0));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_tiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_datauser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_profil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_riwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(btn_profil)
                .addGap(28, 28, 28)
                .addComponent(btn_datauser)
                .addGap(27, 27, 27)
                .addComponent(btn_tiket)
                .addGap(29, 29, 29)
                .addComponent(btn_riwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addGap(53, 53, 53))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.CardLayout());

        PROFIL_ADMIN.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("PROFIL");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("NAMA ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("NO HP");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("ALAMAT");

        txt_pnama.setEditable(false);

        txt_pemail.setEditable(false);

        txt_pnohp.setEditable(false);

        jScrollPane1.setEnabled(false);

        txt_palamat.setEditable(false);
        txt_palamat.setColumns(20);
        txt_palamat.setRows(5);
        jScrollPane1.setViewportView(txt_palamat);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("PASSWORD");

        txt_ppassword.setEditable(false);

        btn_pedit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_pedit.setText("EDIT");
        btn_pedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_peditActionPerformed(evt);
            }
        });

        btn_psave.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_psave.setText("SAVE");
        btn_psave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_psaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PROFIL_ADMINLayout = new javax.swing.GroupLayout(PROFIL_ADMIN);
        PROFIL_ADMIN.setLayout(PROFIL_ADMINLayout);
        PROFIL_ADMINLayout.setHorizontalGroup(
            PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PROFIL_ADMINLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PROFIL_ADMINLayout.createSequentialGroup()
                            .addComponent(btn_psave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_pedit))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PROFIL_ADMINLayout.createSequentialGroup()
                            .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(21, 21, 21)
                            .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_ppassword)
                                .addComponent(txt_pnama)
                                .addComponent(txt_pemail)
                                .addComponent(txt_pnohp)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        PROFIL_ADMINLayout.setVerticalGroup(
            PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PROFIL_ADMINLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_pemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_pnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_ppassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(PROFIL_ADMINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pedit)
                    .addComponent(btn_psave))
                .addGap(61, 61, 61))
        );

        jPanel2.add(PROFIL_ADMIN, "card2");

        DATA_USER.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DATA USER");

        tbl_user.setAutoCreateRowSorter(true);
        tbl_user.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID USER", "NAMA", "NO HP", "EMAIL", "ALAMAT"
            }
        ));
        tbl_user.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbl_user.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_user.setMinimumSize(new java.awt.Dimension(1000, 120));
        tbl_user.setRowHeight(30);
        tbl_user.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_user.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_user.setShowGrid(true);
        tbl_user.setSurrendersFocusOnKeystroke(true);
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_user);
        if (tbl_user.getColumnModel().getColumnCount() > 0) {
            tbl_user.getColumnModel().getColumn(0).setMinWidth(150);
            tbl_user.getColumnModel().getColumn(0).setMaxWidth(200);
            tbl_user.getColumnModel().getColumn(1).setMinWidth(150);
            tbl_user.getColumnModel().getColumn(1).setMaxWidth(200);
            tbl_user.getColumnModel().getColumn(2).setMinWidth(150);
            tbl_user.getColumnModel().getColumn(2).setMaxWidth(200);
            tbl_user.getColumnModel().getColumn(3).setMinWidth(150);
            tbl_user.getColumnModel().getColumn(3).setMaxWidth(200);
            tbl_user.getColumnModel().getColumn(4).setMinWidth(150);
            tbl_user.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        btn_ucari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ucari.setText("CARI");
        btn_ucari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ucariActionPerformed(evt);
            }
        });

        cmb_upilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "id_user", "nama_lengkap", "no_hp", "email", "alamat" }));

        btn_uhapus.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_uhapus.setText("HAPUS");
        btn_uhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uhapusActionPerformed(evt);
            }
        });

        btn_uedit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_uedit.setText("EDIT");
        btn_uedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ueditActionPerformed(evt);
            }
        });

        select_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        select_name.setForeground(new java.awt.Color(255, 255, 255));
        select_name.setText("SELECT EMAIL");

        jLabel11.setText("ID USER");

        jLabel12.setText("NAMA");

        jLabel13.setText("NO HP");

        jLabel14.setText("EMAIL");

        jLabel15.setText("ALAMAT");

        Uiduser.setEditable(false);

        Unama.setEditable(false);

        Unohp.setEditable(false);

        Uemail.setEditable(false);

        Ualamat.setEditable(false);
        Ualamat.setColumns(20);
        Ualamat.setRows(5);
        jScrollPane3.setViewportView(Ualamat);

        btn_uedit1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_uedit1.setText("SIMPAN");
        btn_uedit1.setEnabled(false);
        btn_uedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uedit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DATA_USERLayout = new javax.swing.GroupLayout(DATA_USER);
        DATA_USER.setLayout(DATA_USERLayout);
        DATA_USERLayout.setHorizontalGroup(
            DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATA_USERLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DATA_USERLayout.createSequentialGroup()
                        .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DATA_USERLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(select_name, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DATA_USERLayout.createSequentialGroup()
                                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(29, 29, 29)
                                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Uemail, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(Unohp, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(Unama, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(Uiduser)
                                    .addComponent(jScrollPane3)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DATA_USERLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_ucari, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_upilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ucari)
                        .addGap(52, 52, 52))))
            .addGroup(DATA_USERLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_uhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_uedit1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(btn_uedit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        DATA_USERLayout.setVerticalGroup(
            DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATA_USERLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(select_name))
                .addGap(18, 18, 18)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ucari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ucari)
                    .addComponent(cmb_upilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Uiduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Unama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Unohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Uemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DATA_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_uedit)
                    .addComponent(btn_uhapus)
                    .addComponent(btn_uedit1))
                .addGap(17, 17, 17))
        );

        jPanel2.add(DATA_USER, "card3");

        DATA_TIKET.setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("DATA TIKET");

        cmb_tpilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "id_tiket", "bandara", "maskapai", "destinasi", "QTY" }));

        btn_tcari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tcari.setText("CARI");
        btn_tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tcariActionPerformed(evt);
            }
        });

        tbl_tiket.setAutoCreateRowSorter(true);
        tbl_tiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_tiket.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(tbl_tiket);

        btn_thapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_thapus.setText("HAPUS");
        btn_thapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thapusActionPerformed(evt);
            }
        });

        btn_ttambah.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_ttambah.setText("TAMBAH");
        btn_ttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ttambahActionPerformed(evt);
            }
        });

        btn_tedit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_tedit.setText("EDIT");
        btn_tedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_teditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DATA_TIKETLayout = new javax.swing.GroupLayout(DATA_TIKET);
        DATA_TIKET.setLayout(DATA_TIKETLayout);
        DATA_TIKETLayout.setHorizontalGroup(
            DATA_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATA_TIKETLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(DATA_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DATA_TIKETLayout.createSequentialGroup()
                        .addComponent(btn_ttambah)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tedit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(DATA_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DATA_TIKETLayout.createSequentialGroup()
                            .addComponent(txt_tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmb_tpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_tcari)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_thapus))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        DATA_TIKETLayout.setVerticalGroup(
            DATA_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DATA_TIKETLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(34, 34, 34)
                .addGroup(DATA_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_tpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tcari)
                    .addComponent(btn_thapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DATA_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ttambah)
                    .addComponent(btn_tedit))
                .addGap(8, 8, 8))
        );

        jPanel2.add(DATA_TIKET, "card4");

        RIWAYAT.setBackground(new java.awt.Color(0, 153, 153));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("RIWAYAT");

        tbl_riwayat.setAutoCreateRowSorter(true);
        tbl_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_riwayat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(tbl_riwayat);

        javax.swing.GroupLayout RIWAYATLayout = new javax.swing.GroupLayout(RIWAYAT);
        RIWAYAT.setLayout(RIWAYATLayout);
        RIWAYATLayout.setHorizontalGroup(
            RIWAYATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RIWAYATLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(RIWAYATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        RIWAYATLayout.setVerticalGroup(
            RIWAYATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RIWAYATLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.add(RIWAYAT, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profilActionPerformed
        // TODO add your handling code here:
        PROFIL_ADMIN.setVisible(true);
        DATA_USER.setVisible(false);
        DATA_TIKET.setVisible(false);
        RIWAYAT.setVisible(false);
    }//GEN-LAST:event_btn_profilActionPerformed

    private void btn_ucariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ucariActionPerformed
        // TODO add your handling code here:
        String pilih = (String) cmb_upilih.getSelectedItem();
        
        if(pilih.equals("pilih")){
            JOptionPane.showMessageDialog(rootPane, "Pastikan Anda Memilih Data Untuk Sortir Data !!!");
            getTableUser();
        }else{
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID USER");
            model.addColumn("NAMA LENGKAP");
            model.addColumn("NO HP");
            model.addColumn("EMAIL");
            model.addColumn("ALAMAT");
            try {
                String sql = "select id_user, nama_lengkap, no_hp, email, alamat from tb_user where "+pilih+"='"+txt_ucari.getText()+"'";
                java.sql.Connection conn= database.ConnectDB.configDB();
                java.sql.Statement stm=conn.createStatement();
                java.sql.ResultSet res=stm.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
                }
                tbl_user.setModel(model);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
            }
        }
        
    }//GEN-LAST:event_btn_ucariActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        new PemesananTiketPesawat.Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_peditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_peditActionPerformed
        // TODO add your handling code here:[153,204,255]
        txt_pnama.setEditable(true);
        txt_pnama.setBackground(Color.getHSBColor(153, 204, 255));
        txt_pemail.setEditable(true);
        txt_pemail.setBackground(Color.getHSBColor(153, 204, 255));
        txt_pnohp.setEditable(true);
        txt_pnohp.setBackground(Color.getHSBColor(153, 204, 255));
        txt_ppassword.setEditable(true);
        txt_ppassword.setBackground(Color.getHSBColor(153, 204, 255));
        txt_palamat.setEditable(true);
        txt_palamat.setBackground(Color.getHSBColor(153, 204, 255));
    }//GEN-LAST:event_btn_peditActionPerformed

    private void btn_psaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_psaveActionPerformed
        // TODO add your handling code here:
        try {
                MyData data = new MyData();
                String sql = "UPDATE `tb_user` SET `nama_lengkap`='"+txt_pnama.getText()+"',`no_hp`='"+txt_pnohp.getText()+"',`email`='"+txt_pemail.getText()+"',`password`='"+String.valueOf(txt_ppassword.getPassword())+"',`alamat`='"+txt_palamat.getText()+"' WHERE email = '"+data.getEmail()+"'";
                java.sql.Connection conn = ConnectDB.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Pembaruan Data Berhasil");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        txt_pnama.setEditable(false);
        txt_pnama.setBackground(Color.getHSBColor(242, 242, 242));
        txt_pemail.setEditable(false);
        txt_pemail.setBackground(Color.getHSBColor(242, 242, 242));
        txt_pnohp.setEditable(false);
        txt_pnohp.setBackground(Color.getHSBColor(242, 242, 242));
        txt_ppassword.setEditable(false);
        txt_ppassword.setBackground(Color.getHSBColor(242, 242, 242));
        txt_palamat.setEditable(false);
        txt_palamat.setBackground(Color.getHSBColor(242, 242, 242));
    }//GEN-LAST:event_btn_psaveActionPerformed

    private void btn_datauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datauserActionPerformed
        // TODO add your handling code here:
        PROFIL_ADMIN.setVisible(false);
        DATA_USER.setVisible(true);
        DATA_TIKET.setVisible(false);
        RIWAYAT.setVisible(false);
        getTableUser();
    }//GEN-LAST:event_btn_datauserActionPerformed

    private void btn_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tiketActionPerformed
        // TODO add your handling code here:
        PROFIL_ADMIN.setVisible(false);
        DATA_USER.setVisible(false);
        DATA_TIKET.setVisible(true);
        RIWAYAT.setVisible(false);
        getTableTiket();
    }//GEN-LAST:event_btn_tiketActionPerformed

    private void btn_riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_riwayatActionPerformed
        // TODO add your handling code here:
        PROFIL_ADMIN.setVisible(false);
        DATA_USER.setVisible(false);
        DATA_TIKET.setVisible(false);
        RIWAYAT.setVisible(true);
        getTableRiwayat();
    }//GEN-LAST:event_btn_riwayatActionPerformed

    private void btn_uhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uhapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM tb_user WHERE `tb_user`.`email` = '"+select_name.getText()+"'";
            java.sql.Connection conn = ConnectDB.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penghapusan Data Berhasil");
            getTableUser();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btn_uhapusActionPerformed

    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked
        // TODO add your handling code here:
        int baris = tbl_user.rowAtPoint(evt.getPoint());
        String setSelect = (String) tbl_user.getValueAt(baris, 3);
        Uiduser.setText((String) tbl_user.getValueAt(baris, 0));
        Unama.setText((String) tbl_user.getValueAt(baris, 1));
        Unohp.setText((String) tbl_user.getValueAt(baris, 2));
        Uemail.setText((String) tbl_user.getValueAt(baris, 3));
        Ualamat.setText((String) tbl_user.getValueAt(baris, 4));
        select_name.setText(setSelect);
    }//GEN-LAST:event_tbl_userMouseClicked

    private void btn_ueditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ueditActionPerformed
        // TODO add your handling code here:
        //int collums = tbl_user.getSelectedColumn();
        try{
            int row = tbl_user.getSelectedRow();
            if(row == -1){
                JOptionPane.showMessageDialog(rootPane, "PILIH DATA TELEBIH DULU !!!");
            }else{
                btn_uedit1.setEnabled(true);
                btn_uedit.setEnabled(false);
                Uiduser.setEditable(true);
                Unama.setEditable(true);
                Unohp.setEditable(true);
                Uemail.setEditable(true);
                Ualamat.setEditable(true);
            }
        }catch (HeadlessException ex){
            JOptionPane.showMessageDialog(rootPane, "PILIH DATA TELEBIH DULU !!!");
        }
    }//GEN-LAST:event_btn_ueditActionPerformed

    private void btn_ttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ttambahActionPerformed
        // TODO add your handling code here:
        new FormTiket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ttambahActionPerformed

    private void btn_tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tcariActionPerformed
        // TODO add your handling code here:
        String pilih = (String) cmb_tpilih.getSelectedItem();
        if(pilih.equals("pilih")){
            JOptionPane.showMessageDialog(rootPane, "Pastikan Anda Memilih Data Untuk Sortir Data !!!");
            getTableTiket();
        }else{
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("id_tiket");
            model.addColumn("bandara");
            model.addColumn("maskapai");
            model.addColumn("destinasi");
            model.addColumn("QTY");
            try {
                String sql = "select * from tb_tiket where "+pilih+"='"+txt_tcari.getText()+"'";
                java.sql.Connection conn= database.ConnectDB.configDB();
                java.sql.Statement stm=conn.createStatement();
                java.sql.ResultSet res=stm.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
                }
                tbl_tiket.setModel(model);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
            }
        }
    }//GEN-LAST:event_btn_tcariActionPerformed

    private void btn_thapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thapusActionPerformed
        // TODO add your handling code here:
        try {
            String id = (String) tbl_tiket.getValueAt(tbl_tiket.getSelectedRow(), 0);
            String sql = "DELETE FROM tb_tiket WHERE `tb_tiket`.`id_tiket` = "+id+"";
            java.sql.Connection conn = ConnectDB.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penghapusan Data Berhasil");
            getTableTiket();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_thapusActionPerformed

    private void btn_teditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_teditActionPerformed
        // TODO add your handling code here:
        //int collums = tbl_user.getSelectedColumn();
        try{
                int row = tbl_tiket.getSelectedRow();
                FormTiket.id_tiket = (String) tbl_tiket.getValueAt(row, 0);
                FormTiket.bandara = (String) tbl_tiket.getValueAt(row, 1);
                FormTiket.maskapai = (String) tbl_tiket.getValueAt(row, 2);
                FormTiket.destinasi = (String) tbl_tiket.getValueAt(row, 3);
                FormTiket.QTY = (String) tbl_tiket.getValueAt(row, 4);
                new FormTiket().setVisible(true);
                this.dispose();
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane, "PILIH DATA TELEBIH DULU !!!"+ex);
        }
    }//GEN-LAST:event_btn_teditActionPerformed

    private void btn_uedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uedit1ActionPerformed
        // TODO add your handling code here:
        try {   
                btn_uedit.setEnabled(true);
                btn_uedit1.setEnabled(false);
                Uiduser.setEditable(false);
                Unama.setEditable(false);
                Unohp.setEditable(false);
                Uemail.setEditable(false);
                Ualamat.setEditable(false);
                String selectIndex = Uiduser.getText();
                String selectNama = Unama.getText();
                String selectNOHP = Unohp.getText();
                String selectEmail = Uemail.getText();
                String selectAlamat = Ualamat.getText();

                String sql = "UPDATE `tb_user` SET `nama_lengkap`='"+selectNama+"',`no_hp`='"+selectNOHP+"',`email`='"+selectEmail+"',`alamat`='"+selectAlamat+"' WHERE id_user = '"+selectIndex+"'";
                java.sql.Connection conn = ConnectDB.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Pengeditan Data Berhasil");
                getTableUser();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR"+e);
        }
    }//GEN-LAST:event_btn_uedit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DATA_TIKET;
    private javax.swing.JPanel DATA_USER;
    private javax.swing.JPanel PROFIL_ADMIN;
    private javax.swing.JPanel RIWAYAT;
    private javax.swing.JTextArea Ualamat;
    private javax.swing.JTextField Uemail;
    private javax.swing.JTextField Uiduser;
    private javax.swing.JTextField Unama;
    private javax.swing.JTextField Unohp;
    private javax.swing.JButton btn_datauser;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pedit;
    private javax.swing.JButton btn_profil;
    private javax.swing.JButton btn_psave;
    private javax.swing.JButton btn_riwayat;
    private javax.swing.JButton btn_tcari;
    private javax.swing.JButton btn_tedit;
    private javax.swing.JButton btn_thapus;
    private javax.swing.JButton btn_tiket;
    private javax.swing.JButton btn_ttambah;
    private javax.swing.JButton btn_ucari;
    private javax.swing.JButton btn_uedit;
    private javax.swing.JButton btn_uedit1;
    private javax.swing.JButton btn_uhapus;
    private javax.swing.JComboBox<String> cmb_tpilih;
    private javax.swing.JComboBox<String> cmb_upilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel select_name;
    private javax.swing.JTable tbl_riwayat;
    private javax.swing.JTable tbl_tiket;
    private javax.swing.JTable tbl_user;
    private javax.swing.JTextArea txt_palamat;
    private javax.swing.JTextField txt_pemail;
    private javax.swing.JTextField txt_pnama;
    private javax.swing.JTextField txt_pnohp;
    private javax.swing.JPasswordField txt_ppassword;
    private javax.swing.JTextField txt_tcari;
    private javax.swing.JTextField txt_ucari;
    // End of variables declaration//GEN-END:variables
}
