/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desain_interface;

import static desain_interface.Hasil.*;

/**
 *
 * @author user
 */
public class Frame_uji_rpl extends javax.swing.JFrame {

    /**
     * Creates new form Frame_uji_rpl
     */
    public Frame_uji_rpl() {
        initComponents();
        getSelect();
    }
    
    public void getSelect(){
        if(Hasil.data_hasil_RPL[0]==true){ r1a.setSelected(true);}
        if(Hasil.data_hasil_RPL[0]==false){ r1b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[1]==true){ r2a.setSelected(true);}
        if(Hasil.data_hasil_RPL[1]==false){ r2b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[2]==true){ r3a.setSelected(true);}
        if(Hasil.data_hasil_RPL[2]==false){ r3b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[3]==true){ r4a.setSelected(true);}
        if(Hasil.data_hasil_RPL[3]==false){ r4b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[4]==true){ r5a.setSelected(true);}
        if(Hasil.data_hasil_RPL[4]==false){ r5b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[5]==true){ r6a.setSelected(true);}
        if(Hasil.data_hasil_RPL[5]==false){ r6b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[6]==true){ r7a.setSelected(true);}
        if(Hasil.data_hasil_RPL[6]==false){ r7b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[7]==true){ r8a.setSelected(true);}
        if(Hasil.data_hasil_RPL[7]==false){ r8b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[8]==true){ r9a.setSelected(true);}
        if(Hasil.data_hasil_RPL[8]==false){ r9b.setSelected(true);}
        
        if(Hasil.data_hasil_RPL[9]==true){ r10a.setSelected(true);}
        if(Hasil.data_hasil_RPL[9]==false){ r10b.setSelected(true);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        r1a = new javax.swing.JCheckBox();
        r2a = new javax.swing.JCheckBox();
        r3a = new javax.swing.JCheckBox();
        r5a = new javax.swing.JCheckBox();
        r4a = new javax.swing.JCheckBox();
        r1b = new javax.swing.JCheckBox();
        r2b = new javax.swing.JCheckBox();
        r3b = new javax.swing.JCheckBox();
        r5b = new javax.swing.JCheckBox();
        r4b = new javax.swing.JCheckBox();
        r6b = new javax.swing.JCheckBox();
        r6a = new javax.swing.JCheckBox();
        r7a = new javax.swing.JCheckBox();
        r8a = new javax.swing.JCheckBox();
        r9a = new javax.swing.JCheckBox();
        r10a = new javax.swing.JCheckBox();
        r7b = new javax.swing.JCheckBox();
        r8b = new javax.swing.JCheckBox();
        r9b = new javax.swing.JCheckBox();
        r10b = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("REKAYASA PERANGKAT LUNAK");

        jLabel2.setText("Jawablah pertanyaan dibawah ini dengan memilih jawaban Ya atau Tidak, sesuaikan dengan minat & kemampuan yang dimiliki mahasiswa ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("1. Apakah anda tertarik belajar perangkat lunak? ");

        jLabel4.setText("2. Apakah anda suka desain ? ");

        jLabel5.setText("3. Apakah anda menyukai codingan ? ");

        jLabel6.setText("4. Apakah anda tertarik dengan algoritma ? ");

        jLabel7.setText("5. Apakah anda suka analisa dan perancangan? ");

        jLabel8.setText("6. Apakah anda suka perakitan? ");

        jLabel9.setText("7. Apakah anda minat menjadi seorang software engineer? ");

        jLabel10.setText("8. Apakah anda menyukai game? ");

        jLabel11.setText("9. Apakah anda mengikuti perkembangan pembuatan software? ");

        jLabel12.setText("10. Apakah sebelumnya sudah pernah mendengar/mengetahui konsentrasi ini? ");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("SIMPAN ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r1a);
        r1a.setText("Ya");
        r1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1aActionPerformed(evt);
            }
        });

        buttonGroup2.add(r2a);
        r2a.setText("Ya");
        r2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2aActionPerformed(evt);
            }
        });

        buttonGroup3.add(r3a);
        r3a.setText("Ya");
        r3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3aActionPerformed(evt);
            }
        });

        buttonGroup5.add(r5a);
        r5a.setText("Ya");
        r5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5aActionPerformed(evt);
            }
        });

        buttonGroup4.add(r4a);
        r4a.setText("Ya");
        r4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4aActionPerformed(evt);
            }
        });

        buttonGroup1.add(r1b);
        r1b.setText("Tidak");

        buttonGroup2.add(r2b);
        r2b.setText("Tidak");

        buttonGroup3.add(r3b);
        r3b.setText("Tidak");

        buttonGroup5.add(r5b);
        r5b.setText("Tidak");

        buttonGroup4.add(r4b);
        r4b.setText("Tidak");

        buttonGroup6.add(r6b);
        r6b.setText("Tidak");

        buttonGroup6.add(r6a);
        r6a.setText("Ya");
        r6a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6aActionPerformed(evt);
            }
        });

        buttonGroup7.add(r7a);
        r7a.setText("Ya");
        r7a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7aActionPerformed(evt);
            }
        });

        buttonGroup8.add(r8a);
        r8a.setText("Ya");
        r8a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8aActionPerformed(evt);
            }
        });

        buttonGroup9.add(r9a);
        r9a.setText("Ya");
        r9a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9aActionPerformed(evt);
            }
        });

        buttonGroup10.add(r10a);
        r10a.setText("Ya");
        r10a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r10aActionPerformed(evt);
            }
        });

        buttonGroup7.add(r7b);
        r7b.setText("Tidak");

        buttonGroup8.add(r8b);
        r8b.setText("Tidak");

        buttonGroup9.add(r9b);
        r9b.setText("Tidak");

        buttonGroup10.add(r10b);
        r10b.setText("Tidak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(r1a)
                                        .addGap(84, 84, 84)
                                        .addComponent(r1b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(r2a)
                                        .addGap(84, 84, 84)
                                        .addComponent(r2b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(r3a)
                                        .addGap(84, 84, 84)
                                        .addComponent(r3b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(r4a)
                                        .addGap(84, 84, 84)
                                        .addComponent(r4b))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(r5a)
                                .addGap(83, 83, 83)
                                .addComponent(r5b))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(r6a)
                                        .addGap(85, 85, 85)
                                        .addComponent(r6b))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(r7a)
                                .addGap(84, 84, 84)
                                .addComponent(r7b))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(r8a)
                                .addGap(84, 84, 84)
                                .addComponent(r8b))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(r9a)
                                .addGap(84, 84, 84)
                                .addComponent(r9b))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(r10a)
                                .addGap(84, 84, 84)
                                .addComponent(r10b)))
                        .addGap(9, 9, 9))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r6b)
                            .addComponent(r6a))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r7a)
                            .addComponent(r7b))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r8a)
                            .addComponent(r8b))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r9a)
                            .addComponent(r9b))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r10b)
                            .addComponent(r10a)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r1a)
                            .addComponent(r1b))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r2a)
                            .addComponent(r2b))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r3a)
                            .addComponent(r3b))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r4a)
                            .addComponent(r4b))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r5b)
                            .addComponent(r5a))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Pengenalan Konsentrasi/Peminatan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem6.setText("Pengujian Minat & Kemampuan");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem3.setText("Hasil Rekomendasi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profil");

        jMenuItem4.setText("Universitas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Info");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void r1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1aActionPerformed

    private void r2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2aActionPerformed

    private void r3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3aActionPerformed

    private void r5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5aActionPerformed

    private void r4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r4aActionPerformed

    private void r6aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6aActionPerformed

    private void r7aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7aActionPerformed

    private void r8aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r8aActionPerformed

    private void r9aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9aActionPerformed

    private void r10aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r10aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r10aActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new Frame_Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengenalan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengujian().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Frame_Hasil().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new Frame_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(r1a.isSelected()){ data_hasil_RPL[0] = true; }
        if(r1b.isSelected()){ data_hasil_RPL[0] = false; }
        
        if(r2a.isSelected()){ data_hasil_RPL[1] = true; }
        if(r2b.isSelected()){ data_hasil_RPL[1] = false; }
        
        if(r3a.isSelected()){ data_hasil_RPL[2] = true; }
        if(r3b.isSelected()){ data_hasil_RPL[2] = false; }
        
        if(r4a.isSelected()){ data_hasil_RPL[3] = true; }
        if(r4b.isSelected()){ data_hasil_RPL[3] = false; }
        
        if(r5a.isSelected()){ data_hasil_RPL[4] = true; }
        if(r5b.isSelected()){ data_hasil_RPL[4] = false; }
        
        if(r6a.isSelected()){ data_hasil_RPL[5] = true; }
        if(r6b.isSelected()){ data_hasil_RPL[5] = false; }
        
        if(r7a.isSelected()){ data_hasil_RPL[6] = true; }
        if(r7b.isSelected()){ data_hasil_RPL[6] = false; }
        
        if(r8a.isSelected()){ data_hasil_RPL[7] = true; }
        if(r8b.isSelected()){ data_hasil_RPL[7] = false; }
        
        if(r9a.isSelected()){ data_hasil_RPL[8] = true; }
        if(r9b.isSelected()){ data_hasil_RPL[8] = false; }
        
        if(r10a.isSelected()){ data_hasil_RPL[9] = true; }
        if(r10b.isSelected()){ data_hasil_RPL[9] = false; }
        
        new Frame_Menu_Pengujian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the coRPLand line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_rpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_rpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_rpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_rpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_uji_rpl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox r10a;
    private javax.swing.JCheckBox r10b;
    private javax.swing.JCheckBox r1a;
    private javax.swing.JCheckBox r1b;
    private javax.swing.JCheckBox r2a;
    private javax.swing.JCheckBox r2b;
    private javax.swing.JCheckBox r3a;
    private javax.swing.JCheckBox r3b;
    private javax.swing.JCheckBox r4a;
    private javax.swing.JCheckBox r4b;
    private javax.swing.JCheckBox r5a;
    private javax.swing.JCheckBox r5b;
    private javax.swing.JCheckBox r6a;
    private javax.swing.JCheckBox r6b;
    private javax.swing.JCheckBox r7a;
    private javax.swing.JCheckBox r7b;
    private javax.swing.JCheckBox r8a;
    private javax.swing.JCheckBox r8b;
    private javax.swing.JCheckBox r9a;
    private javax.swing.JCheckBox r9b;
    // End of variables declaration//GEN-END:variables
}
