
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desain_interface;

import static desain_interface.Hasil.*;
import javax.swing.JCheckBox;

/**
 *
 * @author user
 */
public class Frame_Uji_Sig extends javax.swing.JFrame {
    
    public int getHasil;
    public Frame_Uji_Sig() {
        initComponents();
        getSelect();
        
    }
    
    public void getSelect(){
    Hasil hasil = new Hasil();
        if(Hasil.data_hasil_SIG[0]==true){ s1a.setSelected(true);}
        if(Hasil.data_hasil_SIG[0]==false){ s1b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[1]==true){ s2a.setSelected(true);}
        if(Hasil.data_hasil_SIG[1]==false){ s2b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[2]==true){ s3a.setSelected(true);}
        if(Hasil.data_hasil_SIG[2]==false){ s3b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[3]==true){ s4a.setSelected(true);}
        if(Hasil.data_hasil_SIG[3]==false){ s4b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[4]==true){ s5a.setSelected(true);}
        if(Hasil.data_hasil_SIG[4]==false){ s5b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[5]==true){ s6a.setSelected(true);}
        if(Hasil.data_hasil_SIG[5]==false){ s6b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[6]==true){ s7a.setSelected(true);}
        if(Hasil.data_hasil_SIG[6]==false){ s7b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[7]==true){ s8a.setSelected(true);}
        if(Hasil.data_hasil_SIG[7]==false){ s8b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[8]==true){ s9a.setSelected(true);}
        if(Hasil.data_hasil_SIG[8]==false){ s9b.setSelected(true);}
        
        if(Hasil.data_hasil_SIG[9]==true){ s10a.setSelected(true);}
        if(Hasil.data_hasil_SIG[9]==false){ s10b.setSelected(true);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        s2a = new javax.swing.JCheckBox();
        s3a = new javax.swing.JCheckBox();
        s1a = new javax.swing.JCheckBox();
        s4a = new javax.swing.JCheckBox();
        s1b = new javax.swing.JCheckBox();
        s2b = new javax.swing.JCheckBox();
        s3b = new javax.swing.JCheckBox();
        s4b = new javax.swing.JCheckBox();
        s6a = new javax.swing.JCheckBox();
        s7a = new javax.swing.JCheckBox();
        s8a = new javax.swing.JCheckBox();
        s9a = new javax.swing.JCheckBox();
        s6b = new javax.swing.JCheckBox();
        s7b = new javax.swing.JCheckBox();
        s8b = new javax.swing.JCheckBox();
        s9b = new javax.swing.JCheckBox();
        s10b = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        s10a = new javax.swing.JCheckBox();
        s5a = new javax.swing.JCheckBox();
        s5b = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI GEOGRAFIS");

        jLabel2.setText("Jawablah pertanyaan dibawah ini dengan memilih jawaban Ya atau Tidak, sesuaikan dengan minat & kemampuan yang dimiliki mahasiswa ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(466, 466, 466))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("1. Apakah sebelumnya sudah pernah mendengar/mengetahui konsentrasi ini? ");

        jLabel4.setText("2. Apakah anda tertarik dengan sesuatu yang berkaitan dengan alam? ");

        jLabel5.setText("3. Apakah anda menyukai kegiatan traveling? ");

        jLabel6.setText("4. Apakah anda bisa melihat arah kompas dengan baik? ");

        jLabel7.setText("5. Apakah anda bisa menentukan titik koordinat suatu lokasi? ");

        jLabel8.setText("6. Apakah anda mengetahui beberapa jenis tanah? ");

        jLabel9.setText("7. Apakah anda mahir menggunakan aplikasi ArcGis? ");

        jLabel10.setText("8. Apakah anda menyukai proses pembuatan peta?");

        jLabel11.setText("9. Apakah anda menyukai mata kuliah sistem informasi geografis? ");

        jLabel12.setText("10. Apakah apakah menurut anda konsentrasi ini cocok untuk anda? ");

        buttonGroup2.add(s2a);
        s2a.setText("Ya");

        buttonGroup3.add(s3a);
        s3a.setText("Ya");

        buttonGroup1.add(s1a);
        s1a.setText("Ya");
        s1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1aActionPerformed(evt);
            }
        });

        buttonGroup4.add(s4a);
        s4a.setText("Ya");
        s4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4aActionPerformed(evt);
            }
        });

        buttonGroup1.add(s1b);
        s1b.setText("Tidak");

        buttonGroup2.add(s2b);
        s2b.setText("Tidak");

        buttonGroup3.add(s3b);
        s3b.setText("Tidak");

        buttonGroup4.add(s4b);
        s4b.setText("Tidak");

        buttonGroup6.add(s6a);
        s6a.setText("Ya");

        buttonGroup7.add(s7a);
        s7a.setText("Ya");

        buttonGroup8.add(s8a);
        s8a.setText("Ya");

        buttonGroup9.add(s9a);
        s9a.setText("Ya");

        buttonGroup6.add(s6b);
        s6b.setText("Tidak");

        buttonGroup7.add(s7b);
        s7b.setText("Tidak");

        buttonGroup8.add(s8b);
        s8b.setText("Tidak");

        buttonGroup9.add(s9b);
        s9b.setText("Tidak");

        buttonGroup10.add(s10b);
        s10b.setText("Tidak");
        s10b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10bActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("SIMPAN ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup10.add(s10a);
        s10a.setText("Ya");

        buttonGroup5.add(s5a);
        s5a.setText("Ya");

        buttonGroup5.add(s5b);
        s5b.setText("Tidak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(s2a)
                                        .addGap(87, 87, 87)
                                        .addComponent(s2b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(s3a)
                                        .addGap(84, 84, 84)
                                        .addComponent(s3b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(s1a)
                                        .addGap(84, 84, 84)
                                        .addComponent(s1b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(s4a)
                                        .addGap(83, 83, 83)
                                        .addComponent(s4b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(s5a)
                                        .addGap(84, 84, 84)
                                        .addComponent(s5b))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(s8a)
                                        .addGap(80, 80, 80)
                                        .addComponent(s8b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(s9a)
                                        .addGap(80, 80, 80)
                                        .addComponent(s9b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(s6a)
                                        .addGap(75, 75, 75)
                                        .addComponent(s6b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(s7a)
                                        .addGap(79, 79, 79)
                                        .addComponent(s7b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(s10a)
                                        .addGap(81, 81, 81)
                                        .addComponent(s10b))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGap(56, 56, 56))))
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(s1a)
                                    .addComponent(s1b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(s2a)
                                    .addComponent(s2b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(s3a)
                                    .addComponent(s3b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s4a)
                                    .addComponent(s4b)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jLabel7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s5a)
                            .addComponent(s5b)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s6a)
                            .addComponent(s6b))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s7a)
                            .addComponent(s7b))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s8a)
                            .addComponent(s8b))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s9a)
                            .addComponent(s9b))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s10a)
                            .addComponent(s10b))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Pengenalan Konsentrasi/Peminatan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Pengujian Minat & Kemampuan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Hasil Rekomendasi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profil");

        jMenuItem4.setText("Universitas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Info");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void s1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1aActionPerformed

    private void s4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s4aActionPerformed

    private void s10bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s10bActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new Frame_Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengenalan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengujian().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Frame_Hasil().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new Frame_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(s1a.isSelected()){ data_hasil_SIG[0] = true; }
        if(s1b.isSelected()){ data_hasil_SIG[0] = false; }
        
        if(s2a.isSelected()){ data_hasil_SIG[1] = true; }
        if(s2b.isSelected()){ data_hasil_SIG[1] = false; }
        
        if(s3a.isSelected()){ data_hasil_SIG[2] = true; }
        if(s3b.isSelected()){ data_hasil_SIG[2] = false; }
        
        if(s4a.isSelected()){ data_hasil_SIG[3] = true; }
        if(s4b.isSelected()){ data_hasil_SIG[3] = false; }
        
        if(s5a.isSelected()){ data_hasil_SIG[4] = true; }
        if(s5b.isSelected()){ data_hasil_SIG[4] = false; }
        
        if(s6a.isSelected()){ data_hasil_SIG[5] = true; }
        if(s6b.isSelected()){ data_hasil_SIG[5] = false; }
        
        if(s7a.isSelected()){ data_hasil_SIG[6] = true; }
        if(s7b.isSelected()){ data_hasil_SIG[6] = false; }
        
        if(s8a.isSelected()){ data_hasil_SIG[7] = true; }
        if(s8b.isSelected()){ data_hasil_SIG[7] = false; }
        
        if(s9a.isSelected()){ data_hasil_SIG[8] = true; }
        if(s9b.isSelected()){ data_hasil_SIG[8] = false; }
        
        if(s10a.isSelected()){ data_hasil_SIG[9] = true; }
        if(s10b.isSelected()){ data_hasil_SIG[9] = false; }
        
        new Frame_Menu_Pengujian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Uji_Sig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Uji_Sig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Uji_Sig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Uji_Sig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Uji_Sig().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox s10a;
    private javax.swing.JCheckBox s10b;
    private javax.swing.JCheckBox s1a;
    private javax.swing.JCheckBox s1b;
    private javax.swing.JCheckBox s2a;
    private javax.swing.JCheckBox s2b;
    private javax.swing.JCheckBox s3a;
    private javax.swing.JCheckBox s3b;
    private javax.swing.JCheckBox s4a;
    private javax.swing.JCheckBox s4b;
    private javax.swing.JCheckBox s5a;
    private javax.swing.JCheckBox s5b;
    private javax.swing.JCheckBox s6a;
    private javax.swing.JCheckBox s6b;
    private javax.swing.JCheckBox s7a;
    private javax.swing.JCheckBox s7b;
    private javax.swing.JCheckBox s8a;
    private javax.swing.JCheckBox s8b;
    private javax.swing.JCheckBox s9a;
    private javax.swing.JCheckBox s9b;
    // End of variables declaration//GEN-END:variables
}
