/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desain_interface;

import static desain_interface.Hasil.*;

/**
 *
 * @author user
 */
public class Frame_uji_Web extends javax.swing.JFrame {

    /**
     * Creates new form Frame_uji_Web
     */
    public Frame_uji_Web() {
        initComponents();
        getSelect();
    }
    
    public void getSelect(){
        if(Hasil.data_hasil_WEB[0]==true){ w1a.setSelected(true);}
        if(Hasil.data_hasil_WEB[0]==false){ w1b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[1]==true){ w2a.setSelected(true);}
        if(Hasil.data_hasil_WEB[1]==false){ w2b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[2]==true){ w3a.setSelected(true);}
        if(Hasil.data_hasil_WEB[2]==false){ w3b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[3]==true){ w4a.setSelected(true);}
        if(Hasil.data_hasil_WEB[3]==false){ w4b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[4]==true){ w5a.setSelected(true);}
        if(Hasil.data_hasil_WEB[4]==false){ w5b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[5]==true){ w6a.setSelected(true);}
        if(Hasil.data_hasil_WEB[5]==false){ w6b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[6]==true){ w7a.setSelected(true);}
        if(Hasil.data_hasil_WEB[6]==false){ w7b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[7]==true){ w8a.setSelected(true);}
        if(Hasil.data_hasil_WEB[7]==false){ w8b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[8]==true){ w9a.setSelected(true);}
        if(Hasil.data_hasil_WEB[8]==false){ w9b.setSelected(true);}
        
        if(Hasil.data_hasil_WEB[9]==true){ w10a.setSelected(true);}
        if(Hasil.data_hasil_WEB[9]==false){ w10b.setSelected(true);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        w1a = new javax.swing.JCheckBox();
        w2a = new javax.swing.JCheckBox();
        w3a = new javax.swing.JCheckBox();
        w4a = new javax.swing.JCheckBox();
        w5a = new javax.swing.JCheckBox();
        w6a = new javax.swing.JCheckBox();
        w7a = new javax.swing.JCheckBox();
        w8a = new javax.swing.JCheckBox();
        w9a = new javax.swing.JCheckBox();
        w10a = new javax.swing.JCheckBox();
        w1b = new javax.swing.JCheckBox();
        w2b = new javax.swing.JCheckBox();
        w3b = new javax.swing.JCheckBox();
        w4b = new javax.swing.JCheckBox();
        w5b = new javax.swing.JCheckBox();
        w6b = new javax.swing.JCheckBox();
        w7b = new javax.swing.JCheckBox();
        w8b = new javax.swing.JCheckBox();
        w9b = new javax.swing.JCheckBox();
        w10b = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("WEB");

        jLabel2.setText("Jawablah pertanyaan dibawah ini dengan memilih jawaban Ya atau Tidak, sesuaikan dengan minat & kemampuan yang dimiliki mahasiswa ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("1. Apakah anda menyukai pemrograman? ");

        jLabel4.setText("2. Apakah anda suka konten? ");

        jLabel5.setText("3. Apakah anda suka belajar HTML?");

        jLabel6.setText("4. Apakah anda suka membuat aplikasi?");

        jLabel7.setText("5. Apakah anda suka coding?");

        jLabel8.setText("6. Apakah anda ingin menjadi programmer?");

        jLabel9.setText("7. Apakah anda berminat membuat web versi kalian sendiri?");

        jLabel10.setText("8. Apakah anda menyukai perancangan?");

        jLabel11.setText("9. Apakah anda tertarik dalam membuat website?");

        jLabel12.setText("10. Apakah anda mempunyai dasar dalam membuat website?");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("SIMPAN ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(w1a);
        w1a.setText("Ya");

        buttonGroup2.add(w2a);
        w2a.setText("Ya");

        buttonGroup3.add(w3a);
        w3a.setText("Ya");

        buttonGroup4.add(w4a);
        w4a.setText("Ya");

        buttonGroup5.add(w5a);
        w5a.setText("Ya");

        buttonGroup6.add(w6a);
        w6a.setText("Ya");

        buttonGroup7.add(w7a);
        w7a.setText("Ya");

        buttonGroup8.add(w8a);
        w8a.setText("Ya");

        buttonGroup9.add(w9a);
        w9a.setText("Ya");

        buttonGroup10.add(w10a);
        w10a.setText("Ya");

        buttonGroup1.add(w1b);
        w1b.setText("Tidak");
        w1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w1bActionPerformed(evt);
            }
        });

        buttonGroup2.add(w2b);
        w2b.setText("Tidak");
        w2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w2bActionPerformed(evt);
            }
        });

        buttonGroup3.add(w3b);
        w3b.setText("Tidak");
        w3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w3bActionPerformed(evt);
            }
        });

        buttonGroup4.add(w4b);
        w4b.setText("Tidak");
        w4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w4bActionPerformed(evt);
            }
        });

        buttonGroup5.add(w5b);
        w5b.setText("Tidak");
        w5b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w5bActionPerformed(evt);
            }
        });

        buttonGroup6.add(w6b);
        w6b.setText("Tidak");
        w6b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w6bActionPerformed(evt);
            }
        });

        buttonGroup7.add(w7b);
        w7b.setText("Tidak");
        w7b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w7bActionPerformed(evt);
            }
        });

        buttonGroup8.add(w8b);
        w8b.setText("Tidak");
        w8b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w8bActionPerformed(evt);
            }
        });

        buttonGroup9.add(w9b);
        w9b.setText("Tidak");
        w9b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w9bActionPerformed(evt);
            }
        });

        buttonGroup10.add(w10b);
        w10b.setText("Tidak");
        w10b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w10bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(w1a)
                                        .addGap(81, 81, 81)
                                        .addComponent(w1b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(w2a)
                                        .addGap(83, 83, 83)
                                        .addComponent(w2b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(w3a)
                                        .addGap(85, 85, 85)
                                        .addComponent(w3b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(w4a)
                                        .addGap(85, 85, 85)
                                        .addComponent(w4b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(w5a)
                                        .addGap(83, 83, 83)
                                        .addComponent(w5b)))
                                .addGap(111, 111, 111)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(w6a)
                                        .addGap(72, 72, 72)
                                        .addComponent(w6b))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(w9a)
                                        .addGap(77, 77, 77)
                                        .addComponent(w9b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(w10a)
                                        .addGap(78, 78, 78)
                                        .addComponent(w10b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(w8a)
                                                .addGap(75, 75, 75)
                                                .addComponent(w8b))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(w7a)
                                                .addGap(75, 75, 75)
                                                .addComponent(w7b))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(w1a)
                            .addComponent(w6a)
                            .addComponent(w1b)
                            .addComponent(w6b))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(w2a)
                                .addComponent(w2b))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(w7a)
                                .addComponent(w7b)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(w3a)
                            .addComponent(w8a)
                            .addComponent(w3b)
                            .addComponent(w8b))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(w4a)
                                .addComponent(w4b))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(w9a)
                                .addComponent(w9b)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(w5a)
                            .addComponent(w10a)
                            .addComponent(w5b)
                            .addComponent(w10b)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
        );

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Pengenalan Konsentrasi/Peminatan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Pengujian Minat & Kemampuan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Hasil Rekomendasi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profil");

        jMenuItem4.setText("Universitas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Info");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(w1a.isSelected()){ data_hasil_WEB[0] = true; }
        if(w1b.isSelected()){ data_hasil_WEB[0] = false; }
        
        if(w2a.isSelected()){ data_hasil_WEB[1] = true; }
        if(w2b.isSelected()){ data_hasil_WEB[1] = false; }
        
        if(w3a.isSelected()){ data_hasil_WEB[2] = true; }
        if(w3b.isSelected()){ data_hasil_WEB[2] = false; }
        
        if(w4a.isSelected()){ data_hasil_WEB[3] = true; }
        if(w4b.isSelected()){ data_hasil_WEB[3] = false; }
        
        if(w5a.isSelected()){ data_hasil_WEB[4] = true; }
        if(w5b.isSelected()){ data_hasil_WEB[4] = false; }
        
        if(w6a.isSelected()){ data_hasil_WEB[5] = true; }
        if(w6b.isSelected()){ data_hasil_WEB[5] = false; }
        
        if(w7a.isSelected()){ data_hasil_WEB[6] = true; }
        if(w7b.isSelected()){ data_hasil_WEB[6] = false; }
        
        if(w8a.isSelected()){ data_hasil_WEB[7] = true; }
        if(w8b.isSelected()){ data_hasil_WEB[7] = false; }
        
        if(w9a.isSelected()){ data_hasil_WEB[8] = true; }
        if(w9b.isSelected()){ data_hasil_WEB[8] = false; }
        
        if(w10a.isSelected()){ data_hasil_WEB[9] = true; }
        if(w10b.isSelected()){ data_hasil_WEB[9] = false; }
        
        new Frame_Menu_Pengujian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void w3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w3bActionPerformed

    private void w4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w4bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w4bActionPerformed

    private void w5bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w5bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w5bActionPerformed

    private void w10bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w10bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w10bActionPerformed

    private void w9bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w9bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w9bActionPerformed

    private void w8bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w8bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w8bActionPerformed

    private void w7bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w7bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w7bActionPerformed

    private void w6bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w6bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w6bActionPerformed

    private void w2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w2bActionPerformed

    private void w1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w1bActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new Frame_Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengenalan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengujian().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Frame_Hasil().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new Frame_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_uji_Web().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox w10a;
    private javax.swing.JCheckBox w10b;
    private javax.swing.JCheckBox w1a;
    private javax.swing.JCheckBox w1b;
    private javax.swing.JCheckBox w2a;
    private javax.swing.JCheckBox w2b;
    private javax.swing.JCheckBox w3a;
    private javax.swing.JCheckBox w3b;
    private javax.swing.JCheckBox w4a;
    private javax.swing.JCheckBox w4b;
    private javax.swing.JCheckBox w5a;
    private javax.swing.JCheckBox w5b;
    private javax.swing.JCheckBox w6a;
    private javax.swing.JCheckBox w6b;
    private javax.swing.JCheckBox w7a;
    private javax.swing.JCheckBox w7b;
    private javax.swing.JCheckBox w8a;
    private javax.swing.JCheckBox w8b;
    private javax.swing.JCheckBox w9a;
    private javax.swing.JCheckBox w9b;
    // End of variables declaration//GEN-END:variables
}
