/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desain_interface;

import static desain_interface.Hasil.*;

/**
 *
 * @author user
 */
public class Frame_uji_multimedia extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Frame_uji_multimedia() {
        initComponents();
        getSelect();
    }
    
    public void getSelect(){
        if(Hasil.data_hasil_MM[0]==true){ m1a.setSelected(true);}
        if(Hasil.data_hasil_MM[0]==false){ m1b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[1]==true){ m2a.setSelected(true);}
        if(Hasil.data_hasil_MM[1]==false){ m2b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[2]==true){ m3a.setSelected(true);}
        if(Hasil.data_hasil_MM[2]==false){ m3b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[3]==true){ m4a.setSelected(true);}
        if(Hasil.data_hasil_MM[3]==false){ m4b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[4]==true){ m5a.setSelected(true);}
        if(Hasil.data_hasil_MM[4]==false){ m5b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[5]==true){ m6a.setSelected(true);}
        if(Hasil.data_hasil_MM[5]==false){ m6b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[6]==true){ m7a.setSelected(true);}
        if(Hasil.data_hasil_MM[6]==false){ m7b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[7]==true){ m8a.setSelected(true);}
        if(Hasil.data_hasil_MM[7]==false){ m8b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[8]==true){ m9a.setSelected(true);}
        if(Hasil.data_hasil_MM[8]==false){ m9b.setSelected(true);}
        
        if(Hasil.data_hasil_MM[9]==true){ m10a.setSelected(true);}
        if(Hasil.data_hasil_MM[9]==false){ m10b.setSelected(true);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        m1a = new javax.swing.JCheckBox();
        m2a = new javax.swing.JCheckBox();
        m3a = new javax.swing.JCheckBox();
        m4a = new javax.swing.JCheckBox();
        m5a = new javax.swing.JCheckBox();
        m6a = new javax.swing.JCheckBox();
        m7a = new javax.swing.JCheckBox();
        m8a = new javax.swing.JCheckBox();
        m9a = new javax.swing.JCheckBox();
        m10a = new javax.swing.JCheckBox();
        m1b = new javax.swing.JCheckBox();
        m2b = new javax.swing.JCheckBox();
        m3b = new javax.swing.JCheckBox();
        m4b = new javax.swing.JCheckBox();
        m5b = new javax.swing.JCheckBox();
        m6b = new javax.swing.JCheckBox();
        m7b = new javax.swing.JCheckBox();
        m8b = new javax.swing.JCheckBox();
        m9b = new javax.swing.JCheckBox();
        m10b = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("MULTIMEDIA");

        jLabel2.setText("Jawablah pertanyaan dibawah ini dengan memilih jawaban Ya atau Tidak, sesuaikan dengan minat & kemampuan yang dimiliki mahasiswa ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("SIMPAN ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("1. Apakah sebelumnya sudah pernah mendengar/mengetahui konsentrasi ini? ");

        jLabel4.setText("2. Apakah anda tertarik dengan pemrograman? ");

        jLabel5.setText("3. Apakah anda merasa mampu mendesain media interaktif? ");

        jLabel6.setText("4. Apakah anda tertarik dengan animasi 2D/3D? ");

        jLabel7.setText("5. Apakah anda mempunyai dasar dalam pembuatan animasi 2D/3D? ");

        jLabel8.setText("6. Apakah anda mempunyai minat terhadap ilustrator/animator? ");

        jLabel9.setText("7. Apakah anda tertarik dengan desain grafis? ");

        jLabel10.setText("8. Apakah anda tertarik menjadi seorang content creator? ");

        jLabel11.setText("9. Apakah anda suka mengedit video atau foto? ");

        jLabel12.setText("10. Apakah anda menyukai mata kuliah multimedia? ");

        buttonGroup1.add(m1a);
        m1a.setText("Ya");

        buttonGroup1.add(m2a);
        m2a.setText("Ya");

        buttonGroup3.add(m3a);
        m3a.setText("Ya");

        buttonGroup4.add(m4a);
        m4a.setText("Ya");

        buttonGroup5.add(m5a);
        m5a.setText("Ya");

        buttonGroup6.add(m6a);
        m6a.setText("Ya");

        buttonGroup7.add(m7a);
        m7a.setText("Ya");

        buttonGroup8.add(m8a);
        m8a.setText("Ya");

        buttonGroup9.add(m9a);
        m9a.setText("Ya");

        buttonGroup10.add(m10a);
        m10a.setText("Ya");

        buttonGroup1.add(m1b);
        m1b.setText("Tidak");

        buttonGroup2.add(m2b);
        m2b.setText("Tidak");

        buttonGroup3.add(m3b);
        m3b.setText("Tidak");

        buttonGroup4.add(m4b);
        m4b.setText("Tidak");

        buttonGroup5.add(m5b);
        m5b.setText("Tidak");

        buttonGroup6.add(m6b);
        m6b.setText("Tidak");

        buttonGroup7.add(m7b);
        m7b.setText("Tidak");

        buttonGroup8.add(m8b);
        m8b.setText("Tidak");

        buttonGroup9.add(m9b);
        m9b.setText("Tidak");

        buttonGroup10.add(m10b);
        m10b.setText("Tidak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(367, 367, 367))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(m1a)
                                                .addGap(84, 84, 84)
                                                .addComponent(m1b))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(m2a)
                                                .addGap(84, 84, 84)
                                                .addComponent(m2b))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(m3a)
                                                .addGap(84, 84, 84)
                                                .addComponent(m3b))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(m4a)
                                        .addGap(84, 84, 84)
                                        .addComponent(m4b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(m5a)
                                        .addGap(84, 84, 84)
                                        .addComponent(m5b)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(m6a)
                                        .addGap(84, 84, 84)
                                        .addComponent(m6b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(m7a)
                                        .addGap(86, 86, 86)
                                        .addComponent(m7b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(m8a)
                                        .addGap(84, 84, 84)
                                        .addComponent(m8b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(m9a)
                                        .addGap(84, 84, 84)
                                        .addComponent(m9b))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(m10a)
                                        .addGap(84, 84, 84)
                                        .addComponent(m10b)))))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m1a)
                                    .addComponent(m1b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m2a)
                                    .addComponent(m2b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m3a)
                                    .addComponent(m3b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m4a)
                                    .addComponent(m4b))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m6a)
                                    .addComponent(m6b))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m7a)
                                    .addComponent(m7b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m8a)
                                    .addComponent(m8b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m9a)
                                    .addComponent(m9b))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m5a)
                            .addComponent(m10a)
                            .addComponent(m5b)
                            .addComponent(m10b))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(10, 10, 10))
        );

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Pengenalan Konsentrasi/Peminatan");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem2.setText("Pengujian Minat & Kemampuan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Hasil Rekomendasi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profil");

        jMenuItem4.setText("Universitas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Info");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new Frame_Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengenalan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Frame_Menu_Pengujian().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Frame_Hasil().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new Frame_Info().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(m1a.isSelected()){ data_hasil_MM[0] = true; }
        if(m1b.isSelected()){ data_hasil_MM[0] = false; }
        
        if(m2a.isSelected()){ data_hasil_MM[1] = true; }
        if(m2b.isSelected()){ data_hasil_MM[1] = false; }
        
        if(m3a.isSelected()){ data_hasil_MM[2] = true; }
        if(m3b.isSelected()){ data_hasil_MM[2] = false; }
        
        if(m4a.isSelected()){ data_hasil_MM[3] = true; }
        if(m4b.isSelected()){ data_hasil_MM[3] = false; }
        
        if(m5a.isSelected()){ data_hasil_MM[4] = true; }
        if(m5b.isSelected()){ data_hasil_MM[4] = false; }
        
        if(m6a.isSelected()){ data_hasil_MM[5] = true; }
        if(m6b.isSelected()){ data_hasil_MM[5] = false; }
        
        if(m7a.isSelected()){ data_hasil_MM[6] = true; }
        if(m7b.isSelected()){ data_hasil_MM[6] = false; }
        
        if(m8a.isSelected()){ data_hasil_MM[7] = true; }
        if(m8b.isSelected()){ data_hasil_MM[7] = false; }
        
        if(m9a.isSelected()){ data_hasil_MM[8] = true; }
        if(m9b.isSelected()){ data_hasil_MM[8] = false; }
        
        if(m10a.isSelected()){ data_hasil_MM[9] = true; }
        if(m10b.isSelected()){ data_hasil_MM[9] = false; }
        
        new Frame_Menu_Pengujian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_multimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_multimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_multimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_uji_multimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_uji_multimedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox m10a;
    private javax.swing.JCheckBox m10b;
    private javax.swing.JCheckBox m1a;
    private javax.swing.JCheckBox m1b;
    private javax.swing.JCheckBox m2a;
    private javax.swing.JCheckBox m2b;
    private javax.swing.JCheckBox m3a;
    private javax.swing.JCheckBox m3b;
    private javax.swing.JCheckBox m4a;
    private javax.swing.JCheckBox m4b;
    private javax.swing.JCheckBox m5a;
    private javax.swing.JCheckBox m5b;
    private javax.swing.JCheckBox m6a;
    private javax.swing.JCheckBox m6b;
    private javax.swing.JCheckBox m7a;
    private javax.swing.JCheckBox m7b;
    private javax.swing.JCheckBox m8a;
    private javax.swing.JCheckBox m8b;
    private javax.swing.JCheckBox m9a;
    private javax.swing.JCheckBox m9b;
    // End of variables declaration//GEN-END:variables
}
