/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import database.ConnectDB;
import database.MyData;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.Formatter;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        database.MyData data = new MyData();
        txt_useremail.setText(data.getEmail());
        getProfil();
        getTanggal();
        
    }
    
    public void getRiwayat(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id_penerbangan");
        model.addColumn("nama_lengkap");
        model.addColumn("bandara");
        model.addColumn("maskapai");
        model.addColumn("destinasi");
        model.addColumn("tanggal");
        model.addColumn("jam");
        model.addColumn("kelas");
        model.addColumn("QTY");
        model.addColumn("harga_total");
        try {
            String sql = "select * from tb_riwayat";
            java.sql.Connection conn= database.ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5), res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
        }
    }
    
    public void getTotal(){
        Integer harga = Integer.valueOf(txt_Uharga.getText());
        Integer QTY = Integer.valueOf(txt_Uqty.getText());
        Integer TQTY = Integer.valueOf(sisaQTY.getText());
        txt_Utotal.setText(String.valueOf(harga*QTY));
        sisaQTY.setText(String.valueOf(TQTY-QTY));
    }
    public void getTanggal(){
        Date date = new Date();
        SimpleDateFormat SDF = new SimpleDateFormat("EEEE, dd MMMM YYYY");
        SimpleDateFormat tahun = new SimpleDateFormat("YYYY");
        Calendar cal = new GregorianCalendar(Integer.parseInt(tahun.format(date)), date.getMonth(), date.getDate());
        for (int i = 1; i <= 7; i++) {
           cal.add(Calendar.DAY_OF_MONTH, 1);
           cmb_Utanggal.addItem(SDF.format(cal.getTime()));
        }
    }
    public final void getProfil(){
        database.MyData data = new MyData();
        try {
            String sql = "select nama_lengkap, email, no_hp, password, alamat from tb_user where email='"+data.getEmail()+"'";
            java.sql.Connection conn=ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                txt_usernama.setText(res.getString(1));
                txt_useremail.setText(res.getString(2));
                txt_usernohp.setText(res.getString(3));
                txt_userpassword.setText(res.getString(4));
                txt_useralamat.setText(res.getString(5));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "DATA PROFIL ADA YANG SALAH !!!"+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PROFIL_USER = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_usernama = new javax.swing.JTextField();
        txt_useremail = new javax.swing.JTextField();
        txt_usernohp = new javax.swing.JTextField();
        txt_userpassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_useralamat = new javax.swing.JTextArea();
        btn_useredit = new javax.swing.JButton();
        btn_usersave = new javax.swing.JButton();
        PESAN_TIKET = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_Uid = new javax.swing.JTextField();
        txt_Unama = new javax.swing.JTextField();
        cmb_Ubandara = new javax.swing.JComboBox<>();
        cmb_Umaskapai = new javax.swing.JComboBox<>();
        cmb_Udestinasi = new javax.swing.JComboBox<>();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        RBEkonomi = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        txt_Uqty = new javax.swing.JTextField();
        txt_Uharga = new javax.swing.JTextField();
        txt_Utotal = new javax.swing.JTextField();
        btn_Ubayar = new javax.swing.JButton();
        cmb_Utanggal = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        sisaQTY = new javax.swing.JTextField();
        RIWAYAT_USER = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setText("AIRPAZ ");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PROFIL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PESAN TIKET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RIWAYAT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(60, 60, 60))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.CardLayout());

        PROFIL_USER.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("PROFIL");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("NO HP");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("PASSWORD");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("ALAMAT");

        txt_useralamat.setColumns(20);
        txt_useralamat.setRows(5);
        jScrollPane1.setViewportView(txt_useralamat);

        btn_useredit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_useredit.setText("EDIT");

        btn_usersave.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_usersave.setText("SAVE");

        javax.swing.GroupLayout PROFIL_USERLayout = new javax.swing.GroupLayout(PROFIL_USER);
        PROFIL_USER.setLayout(PROFIL_USERLayout);
        PROFIL_USERLayout.setHorizontalGroup(
            PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PROFIL_USERLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PROFIL_USERLayout.createSequentialGroup()
                            .addComponent(btn_usersave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_useredit))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PROFIL_USERLayout.createSequentialGroup()
                            .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(30, 30, 30)
                            .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_usernama)
                                .addComponent(txt_useremail)
                                .addComponent(txt_usernohp)
                                .addComponent(txt_userpassword)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        PROFIL_USERLayout.setVerticalGroup(
            PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PROFIL_USERLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PROFIL_USERLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_usernama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_useremail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_usernohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_userpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(171, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PROFIL_USERLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PROFIL_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_usersave)
                            .addComponent(btn_useredit))
                        .addGap(68, 68, 68))))
        );

        jPanel2.add(PROFIL_USER, "card2");

        PESAN_TIKET.setBackground(new java.awt.Color(0, 153, 153));
        PESAN_TIKET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PESAN_TIKETMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("PESAN TIKET");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ID PENERBANGAN");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("NAMA");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("BANDARA");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("MASKAPAI");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("DESTINASI");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("TANGGAL");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("JAM");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("KELAS");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("QTY");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("HARGA");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("TOTAL HARGA");

        txt_Uid.setEditable(false);
        txt_Uid.setText("AUTO INSERT");

        txt_Unama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UnamaActionPerformed(evt);
            }
        });

        cmb_Ubandara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cmb_Ubandara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_UbandaraMouseClicked(evt);
            }
        });

        cmb_Umaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cmb_Umaskapai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_UmaskapaiMouseClicked(evt);
            }
        });

        cmb_Udestinasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cmb_Udestinasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_UdestinasiMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("12.00 PM");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("03.00 PM");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("09.00 PM");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("06.00 AM");

        buttonGroup2.add(RBEkonomi);
        RBEkonomi.setText("EKONOMI");
        RBEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEkonomiActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("BISNIS");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("FIRST CLASS");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        txt_Uqty.setText("0");

        txt_Uharga.setEditable(false);
        txt_Uharga.setText("0");

        txt_Utotal.setEditable(false);

        btn_Ubayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Ubayar.setText("BAYAR");
        btn_Ubayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbayarActionPerformed(evt);
            }
        });

        cmb_Utanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));

        jLabel21.setText("SISA QTY");

        sisaQTY.setEditable(false);

        javax.swing.GroupLayout PESAN_TIKETLayout = new javax.swing.GroupLayout(PESAN_TIKET);
        PESAN_TIKET.setLayout(PESAN_TIKETLayout);
        PESAN_TIKETLayout.setHorizontalGroup(
            PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                        .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Uid)
                            .addComponent(txt_Unama, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(cmb_Ubandara, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_Umaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_Udestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                                        .addComponent(jRadioButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton2))
                                    .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                                        .addComponent(RBEkonomi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton7)
                                    .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                                        .addComponent(jRadioButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton4))))
                            .addComponent(txt_Uharga)
                            .addComponent(txt_Utotal)
                            .addComponent(cmb_Utanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                                .addComponent(txt_Uqty, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sisaQTY)))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PESAN_TIKETLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Ubayar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        PESAN_TIKETLayout.setVerticalGroup(
            PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PESAN_TIKETLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_Unama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cmb_Ubandara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cmb_Umaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(cmb_Udestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmb_Utanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(RBEkonomi)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_Uqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(sisaQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_Uharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PESAN_TIKETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_Utotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Ubayar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.add(PESAN_TIKET, "card3");

        RIWAYAT_USER.setBackground(new java.awt.Color(0, 153, 153));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("RIWAYAT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout RIWAYAT_USERLayout = new javax.swing.GroupLayout(RIWAYAT_USER);
        RIWAYAT_USER.setLayout(RIWAYAT_USERLayout);
        RIWAYAT_USERLayout.setHorizontalGroup(
            RIWAYAT_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RIWAYAT_USERLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(RIWAYAT_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        RIWAYAT_USERLayout.setVerticalGroup(
            RIWAYAT_USERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RIWAYAT_USERLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.add(RIWAYAT_USER, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PROFIL_USER.setVisible(false);
        PESAN_TIKET.setVisible(false);
        RIWAYAT_USER.setVisible(true);
        getRiwayat();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_UbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbayarActionPerformed
              
        String Jam = "";
        String Kelas = "";
        if(jRadioButton5.isSelected()){
            Jam = jRadioButton5.getText();
        }if(jRadioButton2.isSelected()){
            Jam = jRadioButton2.getText();
        }if(jRadioButton3.isSelected()){
            Jam = jRadioButton3.getText();
        }if(jRadioButton4.isSelected()){
            Jam = jRadioButton4.getText();
        }if(RBEkonomi.isSelected()){
            Kelas = RBEkonomi.getText();
        }if(jRadioButton6.isSelected()){
            Kelas = jRadioButton6.getText();
        }if(jRadioButton7.isSelected()){
            Kelas = jRadioButton7.getText();
        }
        
//        JOptionPane.showMessageDialog(rootPane, Jam + Kelas);
            try {
                String sql = "INSERT INTO `tb_riwayat`(`nama_lengkap`, `bandara`, `maskapai`, `destinasi`, `tanggal`, `jam`, `kelas`, `QTY`, `harga_total`) "
                        + "VALUES ( '"+txt_Unama.getText()+"','"+cmb_Ubandara.getSelectedItem()+"', '"+cmb_Umaskapai.getSelectedItem()+"','"+cmb_Udestinasi.getSelectedItem()+"',"
                        + "'"+cmb_Utanggal.getSelectedItem()+"', '"+Jam+"','"+Kelas+"','"+txt_Uqty.getText()+"','"+txt_Utotal.getText()+"')";
                java.sql.Connection conn = ConnectDB.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Penambahan Data Berhasil: ");
                new Admin.Home().setVisible(true);
                this.dispose();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
            }
    }//GEN-LAST:event_btn_UbayarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PROFIL_USER.setVisible(true);
        PESAN_TIKET.setVisible(false);
        RIWAYAT_USER.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_Unama.setText(txt_usernama.getText());
        PROFIL_USER.setVisible(false);
        PESAN_TIKET.setVisible(true);
        RIWAYAT_USER.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PESAN_TIKETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PESAN_TIKETMouseClicked
        // TODO add your handling code here:
        getTotal();
    }//GEN-LAST:event_PESAN_TIKETMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new PemesananTiketPesawat.Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_UnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UnamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_UnamaActionPerformed

    private void cmb_UbandaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_UbandaraMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select bandara, QTY from tb_tiket";
            java.sql.Connection conn=ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmb_Ubandara.addItem(res.getString(1));
                sisaQTY.setText(res.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "DATA ADA YANG SALAH !!!"+e);
        }
    }//GEN-LAST:event_cmb_UbandaraMouseClicked

    private void cmb_UmaskapaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_UmaskapaiMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select maskapai from tb_tiket";
            java.sql.Connection conn=ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmb_Umaskapai.addItem(res.getString(1));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "DATA ADA YANG SALAH !!!"+e);
        }
    }//GEN-LAST:event_cmb_UmaskapaiMouseClicked

    private void cmb_UdestinasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_UdestinasiMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select destinasi from tb_tiket";
            java.sql.Connection conn=ConnectDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmb_Udestinasi.addItem(res.getString(1));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "DATA ADA YANG SALAH !!!"+e);
        }
    }//GEN-LAST:event_cmb_UdestinasiMouseClicked

    private void RBEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEkonomiActionPerformed
        // TODO add your handling code here:
        Integer QTY = Integer.valueOf(txt_Uqty.getText());
        Integer harga = 25000;
        Integer total = harga*QTY;
        txt_Uharga.setText(harga.toString());
        txt_Utotal.setText(total.toString());
    }//GEN-LAST:event_RBEkonomiActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        Integer QTY = Integer.valueOf(txt_Uqty.getText());
        Integer harga = 50000;
        Integer total = harga*QTY;
        txt_Uharga.setText(harga.toString());
        txt_Utotal.setText(total.toString());
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        Integer QTY = Integer.valueOf(txt_Uqty.getText());
        Integer harga = 75000;
        Integer total = harga*QTY;
        txt_Uharga.setText(harga.toString());
        txt_Utotal.setText(total.toString());
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PESAN_TIKET;
    private javax.swing.JPanel PROFIL_USER;
    private javax.swing.JRadioButton RBEkonomi;
    private javax.swing.JPanel RIWAYAT_USER;
    private javax.swing.JButton btn_Ubayar;
    private javax.swing.JButton btn_useredit;
    private javax.swing.JButton btn_usersave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb_Ubandara;
    private javax.swing.JComboBox<String> cmb_Udestinasi;
    private javax.swing.JComboBox<String> cmb_Umaskapai;
    private javax.swing.JComboBox<String> cmb_Utanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField sisaQTY;
    private javax.swing.JTextField txt_Uharga;
    private javax.swing.JTextField txt_Uid;
    private javax.swing.JTextField txt_Unama;
    private javax.swing.JTextField txt_Uqty;
    private javax.swing.JTextField txt_Utotal;
    private javax.swing.JTextArea txt_useralamat;
    private javax.swing.JTextField txt_useremail;
    private javax.swing.JTextField txt_usernama;
    private javax.swing.JTextField txt_usernohp;
    private javax.swing.JPasswordField txt_userpassword;
    // End of variables declaration//GEN-END:variables
}
