/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import database.ConnectDB;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author fsdio
 */
public class FormTiket extends javax.swing.JFrame {
    
    // VARIABEL
    public static String id_tiket, nama_tiket, bandara, maskapai, destinasi, tanggal, jam, kelas, QTY, harga;
    /**
     * Creates new form FormData
     */
    public FormTiket() {
        initComponents();
        updateData();
    }
    
    public void updateData(){
        txt_formid.setText(FormTiket.id_tiket);
        txt_formbandara.setText(FormTiket.bandara);
        txt_formmaskapai.setText(FormTiket.maskapai);
        txt_formdestinasi.setText(FormTiket.destinasi);
        txt_formqty.setText(FormTiket.QTY);
    }
    
    public void getDataTiket(){
        if(FormTiket.id_tiket==null){
            try {
                String sql = "INSERT INTO `tb_tiket`(`bandara`, `maskapai`, `destinasi`, `QTY`) VALUES ( '"+txt_formbandara.getText()+"','"+txt_formmaskapai.getText()+"', '"+txt_formdestinasi.getText()+"','"+txt_formqty.getText()+"')";
                java.sql.Connection conn = ConnectDB.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Penambahan Data Berhasil: ");
                new Home().setVisible(true);
                this.dispose();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
            }
        }else{
            try {
                String sql = "UPDATE `tb_tiket` SET "
                        + "`bandara`='"+txt_formbandara.getText()+"',"
                        + "`maskapai`='"+txt_formmaskapai.getText()+"',"
                        + "`destinasi`='"+txt_formdestinasi.getText()+"',"
                        + "`QTY`='"+txt_formqty.getText()+"' "
                        + "WHERE id_tiket = '"+txt_formid.getText()+"'";
                java.sql.Connection conn = ConnectDB.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Pengeditan Data Berhasil: ");
                new Home().setVisible(true);
                this.dispose();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "ERROR : " + e);
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_formid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_formbandara = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_formmaskapai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_formqty = new javax.swing.JTextField();
        txt_formdestinasi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_simpanform = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("ID TIKET");

        txt_formid.setEditable(false);
        txt_formid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_formid.setText("AUTO CREATE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DATA TIKET");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("BANDARA");

        txt_formbandara.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_formbandara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_formbandaraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("MASKAPAI");

        txt_formmaskapai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_formmaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_formmaskapaiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("DESTINASI");

        txt_formqty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt_formdestinasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("QTY");

        btn_simpanform.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_simpanform.setText("SIMPAN");
        btn_simpanform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanformActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpanform)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_formqty, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_formdestinasi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_formmaskapai, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_formbandara, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_formid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formbandara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formmaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formdestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_simpanform)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_formbandaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_formbandaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_formbandaraActionPerformed

    private void txt_formmaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_formmaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_formmaskapaiActionPerformed

    private void btn_simpanformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanformActionPerformed
        // TODO add your handling code here:
        getDataTiket();
    }//GEN-LAST:event_btn_simpanformActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpanform;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_formbandara;
    private javax.swing.JTextField txt_formdestinasi;
    private javax.swing.JTextField txt_formid;
    private javax.swing.JTextField txt_formmaskapai;
    private javax.swing.JTextField txt_formqty;
    // End of variables declaration//GEN-END:variables
}
